[package]
name = "bridge-token-factory"
version = "0.1.0"
authors = ["Near Inc <hello@near.org>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
near-sdk = "0.11.0"
borsh = "0.6.2"
# near-sdk = "1.0.0"
uint = { version = "0.8.3", default-features = false }
wee_alloc = { version = "0.4.5", default-features = false, features = [] }
near-lib = { git = "https://github.com/ilblackdragon/balancer-near" }
eth-types =  { git = "https://github.com/near/rainbow-bridge" }
rlp = "0.4.2"
ethabi = "12.0.0"
hex = "0.4.2"
tiny-keccak = "1.4.0"

[dev-dependencies]
near-test = { git = "https://github.com/ilblackdragon/balancer-near" }
lazy_static = "1.4.0"